dist: xenial
language: go
go:
  - 1.15.x

go_import_path: github.com/application-stacks/runtime-component-operator

services:
  - docker

stages:
  - name: test
  - name: build
    if: branch = master AND fork = false AND type != pull_request
  - name: build manifest
    if: branch = master AND fork = false AND type != pull_request

jobs:
  include:
    - name: Unit testing
      stage: test
      script: make unit-test
    - name: Verify operator image build
      script: make build-image
      if: branch != master OR fork = true OR type = pull_request
    - name: E2E testing on Minikube
      script: make test-minikube
    - name: E2E testing on OCP 4.3
      script: make test-e2e
      if: fork = false
    ## if master branch build and push images on all three archs
    - name: Build image on amd64
      stage: build
      os: linux
      arch: amd64
      script:
        - make build-multiarch-image
        - make build-manifest
    - name: Build image on ppc64le
      os: linux
      arch: ppc64le
      script:
        - make build-multiarch-image
        - make build-manifest
    - name: Build image on s390x
      os: linux
      arch: s390x
      script:
        - make build-multiarch-image
        - make build-manifest
    ## in case there were concurrency issues with building manifest lists
    ## in previous steps, create FAT manifests one last time
    - name: Verify manifest lists
      stage: build manifest
      script: make build-manifest
